### ISSUE TITLE
Cannot use version of SDK - Code 4

### ISSUE THREAD

**Issue by Kumuluzz** [actigraph/ActigraphLinkSDK#1]
# Intro
I'm trying to run the example iOS project, connecting it to my GT9X, but I'm having 2 problems with it. 

# 1) Segue to details
The app doesn't allow segueing to the `DetailViewController` due to the the `UITextView`. This issue is due to some bug in iOS 9 and Xcode 7 apparently:
http://stackoverflow.com/questions/32643765/ios-9-segue-causes-app-to-freeze-no-crash-or-error-thrown

# 2) Connection fails due to SDK
I have simply deleted the `UITextView` for now and examining the output in the debugging console. When I try to connect, then I get the output:

`{"error":{"message":"This device is not able to be used with this SDK.","code":4}}`

Now, it's not very clear which SDK is being referred to. If it is the `ActigraphLinkSDK`, the `iOS SDK` or something third? Furthermore, it doesn't specify if the SDK is too old or too new or how this can be fixed.

# Environment
My environment is:
- OS X, 10.11
- Xcode 7.1 (7B91b)
- iPhone8,1
- iOS 9.1 (13B143)

**Comment by brianbell** [comment]
Thanks for the detailed feedback.  For the first issue, I need to have our IOS developer reply.  For the second issue, this sounds like it's probably due to the licensing requirement.  A CentrePoint license is required to use the GT9X device with the SDK.  If you do have that setup already, we can discuss your use case, pricing, and how to get started.

**Comment by Kumuluzz** [comment]
@brianbell 

Thanks for responding so quickly! 

---

1) I'm looking forward to hearing from him.

---
2) I have a valid CentrePoint license. I've had the device associated with a subject for the last few days, but today I disconnected it from the subject. Could this be causing the issue?

I was facing some issues discovering the device with the SDK in the sample app, but I realised that after I had disconnected the device from the subject, then the device appeared when using the sample app. This is why I disconnected the device from the subject.

===

3) Later I have come to the conclusion that whenever I put the device for charging, then it will activate the bluetooth and turn off after a period of time. Is there a way to have the bluetooth turned on at all times?

**Comment by blitzxion** [comment]
@Kumuluzz 

I'll look into the iOS9 issue with the demo project and see what I can find as a solution (I'll update the project if I find it). You're workaround should suffice in the meantime.

**Comment by brianbell** [comment]
Stefan,

Looks like out iOS expert has chimed in and will look at #1.

I'll check out the expected operation regarding disconnecting the device from the subject and get back to you.  It's about nearly 5pm here so it will be in the morning.  I might reach out to you directly from brian.bell@theactigraph.com to get the name of your CentrePoint study.  This will allow me to check the logs on our end and confirm the device parameters.

Thanks,
Brian

**Comment by brianbell** [comment]
Stefan,

Just giving you an update here.  We found a problem related to your study settings which we can change our our end.

We going to open a support ticket in our internal ticket system to continue correspondence.  Please check your inbox for that today.

Thanks,
Brian
