### ISSUE TITLE
Missing architecture support

### ISSUE THREAD

**Issue by Kumuluzz** [actigraph/ActigraphLinkSDK#2]
# Description
The ActiGraph iOS SDK has only been exported to support the `arm64` architecture, so it doesn't support the `armv7`, `armv7s`, `i386` and `x86_64` archiectures.

This can be confirmed by running the following command:
`lipo -info libAGDeviceSDK.a`

This means the SDK can only be installed on iPhone 5S and above, which is not optimal since iOS 9 is supported all the way down to iPhone 4S. 

Also, it makes it impossible to run any app using the SDK in the simular. Now, of course this is less important since the SDK would interact with a real device anyway due to the fact that bluetooth cannot be tested in the simular.

Lastly, it means that it is impossible to compile and export an app using the SDK unless I change the architecture targets for my own app to match the ones of the ActiGraph SDK.

# Steps to test
This issue can easily be recreated with the simular, but also on specific real devices.

- Open up the ActiGraph iOS demo app
- Try to run it in the simular, doesn't work
- Try to run on an iPhone5 or below, doesn't work
- Try to run on an iPhone 5s or above, works

# Enviroment:
- Swift 2 (for the project where I'm using the SDK)
- Xcode 7.1 (7B91b)
- OS X 10.11 (15A284)
- iPhone8,1 (tested real device, the sdk works)
- iPhone6,2 (tested real device, the sdk works)
- iPhone5,1 (tested real device, the sdk does not work)

# External resources:
iOS Support Matric:
http://static1.squarespace.com/static/51adfbd9e4b095d664d9b869/t/5596a861e4b0eb5f837cf243/1435936865957/iOS_Support_Matrix_v3_2.pdf

**Comment by blitzxion** [comment]
@Kumuluzz 

Thanks for the very descriptive issue! I have reviewed the SDK source and have indeed found that we're not compiling it with the additional architectures.

Support for `i386` and `x86_64` isn't possible within this SDK due to the requirement of Apple's CoreBluetooth library and the simulator's inability to utilize those libraries.

```
$ lipo -info libAGDeviceSDK.a
Architectures in the fat file: libAGDeviceSDK.a are: armv7 arm64 armv7s
```

I'll push an update with these chages shortly.
